# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puphpet/centos65-x64"
  # config.vm.box_url = "<path/to/box/file>"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../shared/www", "/var/www", create: true

  config.vm.hostname = "myproject"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Amount of memory on the VM
    vb.memory = 1024
    # 1/4 of memory
    # vb.memory = `memtotal=$(awk '$1~/MemTotal:/ {print $2}' /proc/meminfo); echo -n $(( (memtotal / 1024) / 4 ))`

    # Amount of CPUs used
    vb.cpus = 2
    # 1/2 of CPUs
    # vb.cpus = `totalcpus=$(grep "processor" /proc/cpuinfo | wc -l); echo -n $(( $totalcpus / 2 ))`
  end

  # Scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh"

  # Puppet
  config.vm.provision "puppet" do |puppet|
    puppet.module_path    = "modules"

    # Puppet 3
    puppet.manifests_path = "environments/development/manifests"
    puppet.manifest_file  = "site.pp"

    # Puppet 4
    # puppet.environment_path = "environments"
    # puppet.environment      = "development"
  end

end