# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puphpet/centos65-x64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../shared/www", "/var/www", create: true

  config.vm.hostname = "myproject"

  # Scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh"

  # Puppet
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "environments/development/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "modules"
  end

end